databases:
  - name: sentiment_db
    databaseName: sentiment_analysis
    user: admin
    plan: free # يمكنك تغييره إلى standard إذا كنت ترغب في أداء أعلى

services:
  - type: web
    name: sentiment-analysis-app
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn sentiment_project.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /healthz/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: sentiment_db
          property: connectionString
